name       : intel-media-driver
version    : 21.3.5
release    : 2
source     :
    - https://github.com/intel/media-driver/archive/refs/tags/intel-media-21.3.5.tar.gz : 182925ed21c0a9843a63865e34dc35bf713294260d14ceb29e8de0de2e34733f
license    :
    - BSD-3-Clause
    - MIT
component  : xorg.display
homepage   : https://github.com/intel/media-driver
summary    : VA-API driver for Intel Gen graphics
description: |
    The Intel Media Driver is a VA-API (Video Acceleration API) user mode driver supporting hardware accelerated decoding, encoding, and video post processing for Intel Gen based graphics hardware.
builddeps  :
    - pkgconfig(igdgmm)
    - pkgconfig(libva)
    - pkgconfig(pciaccess)
setup      : |
    %patch -Np1 < "$pkgfiles/0001-Set-BUILD_TYPE-to-CMAKE_BUILD_TYPE-if-undefined.patch"
    rm -f Tools/MediaDriverTools/UMDPerfProfiler/MediaPerfParser

    export CXXFLAGS="$(echo "$CXXFLAGS" | sed -e 's/-Wall //')"
    %cmake_ninja -Wno-dev \
        -DCMAKE_INSTALL_LIBDIR="%libdir%" \
        -DBUILD_CMRTLIB:BOOL=False \
        -DMEDIA_RUN_TEST_SUITE:BOOL=False
build      : |
    %ninja_build
install    : |
    %ninja_install
